language: go
go_import_path: go.universe.tf/netboot
go:
  - 1.5
  - 1.6
  - tip
os:
  - linux
install:
  - go get github.com/golang/lint/golint
before_script:
script:
  - GO15VENDOREXPERIMENT=1 go get -t ./...
  - GO15VENDOREXPERIMENT=1 go build ./...
  - GO15VENDOREXPERIMENT=1 go test ./...
  - go vet ./...
  - golint ./...
