language: go
go_import_path: go.universe.tf/netboot
go:
- 1.6
- 1.7
- tip
os:
- linux
install:
- go get github.com/Masterminds/glide
- go get github.com/golang/lint/golint
- gem install fpm
before_script: 
script:
- glide install
- go build $(glide novendor)
- go test $(glide novendor)
- go vet $(glide novendor)
- glide novendor | xargs -n1 golint
- fpm -s dir -t deb -n pixiecore -v $(date '+%Y%m%d%H%M%S') --license Apache2 --vendor
  "David Anderson <dave@natulte.net>" --maintainer "David Anderson <dave@natulte.net>"
  --description "All-in-one PXE booting" --url "https://github.com/google/netboot"
  ./pixiecore=/usr/bin/pixiecore
env:
  # packagecloud.io API key
  secure: "S8R+j1uSi0+gZHcEI7lZGkECWXTv50d/g23kKaIH7HHgQO2ljplSE0egkWRr5s0yQnDuBRAw0bLfN9EI2IYo/iTEuBuACoO0fg/FnyJnrlNcugUeejMdbXbAgrI6phTqqr+LGmSAv8sNbSKDppJ8nkfCU0P6GXOyh63JjrnT8J7yeP3evs//Qe/WtMGBsh2o+9FlHldy+E7Vb8HePIwJ+KoOvFByoug3GtZ0yHr26XX0rwmXANo4QrA8TNuk9rGyu/teNrG0IOmAgnb6V3fNjjVJ15EwCM9c9YXtbo1Dz5r2fl8etmkSC0EvKAuTOfoyxEs2UjObu2gxy/Ow6oYvCUtEfBqoWAwlEpcuKjX7S92iNtlzNNcp1jILYAjcbcqwY18kOXfzXWtnSeSdf1DNruvljQuG55Hk7HuXQ+ljjvY4s9jHXN+w6b3IP6nvNhhXL+a3iKJVOzC2PjrXte3PTYiCsEPISAA1NQUNQly6QCUf3Feo0NMRnnh0W5/nZg0qW24rBOp0Y4fM6mh8d8TtpTEfpXacqJFy2q+8ypAR981kRvq81F2aEpFr+7+dHoUom/2k0xotp9VJ9x2b7HQBJGS2AmmT3bFk6ZNh4fLIjsBWy2fqwnq/vFqsJCErkX7q38XVJxbaZGZQ9e3NVGwwne5E/i4u39zOGHVB8XpQgKc="
  # quay.io trigger URL
  secure: "XDV3Wf57zoCQx8BMUxdkYFuioEwJo/WQHO4rA9tbMLgOeDdHiS2gTPnF7OdxXwYuT1jEkBODUBql/U2Xku0b5fhJQV30oUdsL5R8wXR59xSYYUFOF5yg6MfhEdkh8VgcMNQcRGrkdTSHyOZ1ITEqqMAA6w/tg3sD4zLaUx5Ad4TlaHr3xB/1DJdgRbYJp2UMPzbLrmsTC/S/bJ4lEkJiFkUAdWejWKc3ji4ReGoHiYriwtDVvSPZLNucT76c1058KC/KA6r/Mf4Gr6Dn6ixQDa5T+7GWOf8+V/5qvYogURdxcc1faFOJNDnnJp7pe0NYnZHjl0onYN9dTul1gQoyPrq1MvXBvoINXtXWE9y54OWjtybiIasZ4IYpbW9VXylWEoFd+qpweFSAKTdYPXONzNgER3v33+HoRLjYRMrVUd4xgyxGRhwZqj3ankOwana3UhhSd+9SImR7tGUzh2V+NoMZWG3wk+GAP+2ak8SInbjHIHm3ZZ4/TpAtmK/W4yGww0BqQSvxkinS1zUxGCk1ZO33ZAHmutc+hSMr/DmGHKSbQ23lJpALVp/S2r0WgQOkcEnmau1okHupuFnBkLBQqc3dk4auCOWBmu5r24Ea+q0bG/ZPGkKqU9FPlsCQCJ84sn5o8HQ31bFGSRjZUwAazk8notbt7LY1HKfBReqyRMA="

deploy:
- provider: packagecloud
  repository: pixiecore
  username: danderson
  dist: debian/stretch
  skip_cleanup: true
  package_glob: "*"
  token:
    secure: bKYiaKJgHWEubQOv3Z+xb0CVrxNnIWhf11IsDVPYmypTjqZ1RzqkyPo3VVksRi4IC+fndywXjImT0uYDlwLR26zatIGbSxrNPaawKZYmTR/Xm6/gF5AJlteLWUVZAD5O/Nq5rPxQUy5GGxYiDCmG2EB4Y4EYkjxLTwUyC2pqMKhX6vcR+b967cBrffm+AVz0nOEA684jhDq2+igVo4oG7F7U0745YRbhNZHJhftFmxMT7hvMhi/J7ogq2krPyItIrmnkfW/tlV4PJhiIk1p0VDIXLAGQ98VlG0HjUPdIsMla0d+JkswoGG9JPipb91j5i9XSvKhgHry/xaC1NnyraoHbzmrV7MamwDtK8Y3Rghomu+s3bknYz5B0Ft5ifWz6nTUqs7T/AHlnpK3y/zrK9YuQoZ5zQvMnx4xt97AK/2Au87dCP5ProxKIMiPyrc4rNSPzRe0wJu9opizV0EKS34hTOXsw40/bSuqBtBAenBz2qesWay4IT2gQ8BvhkclHnCEczh/+N/8cEAhXKiptRMm0MkbNVvBvLZOQS+S0npXLq1aTb2ROZ3LA9yEsB5LWUV5lLDoPDmFjGHZ6dHjg7l/ZDc5N0LYAiLv6imaScl5e1np85RStji1M5d4Enx7LD3cqXU5WtGHrz/RoH30in10N9g9dpzf7Glqt6hyeSG4=
  on:
    branch: master
    go: '1.7'
- provider: script
  script: go run scripts/prune_old_versions/main.go -user=danderson -repo=pixiecore -distro=debian -version=stretch -package=pixiecore -arch=amd64 -limit=2
  on:
    branch: master
    go: '1.7'
- provider: script
  script: go run scripts/trigger_quay_build/main.go
  on:
    branch: master
    go: '1.7'
