language: go
go_import_path: go.universe.tf/netboot
go:
- 1.6
- 1.7
- tip
os:
- linux
install:
- go get github.com/Masterminds/glide
- go get github.com/golang/lint/golint
- gem install fpm
before_script: 
script:
- glide install
- go build $(glide novendor)
- go test $(glide novendor)
- go vet $(glide novendor)
- glide novendor | xargs -n1 golint
- fpm -s dir -t deb -n pixiecore -v $(date '+%Y%m%d%H%M%S') --license Apache2 --vendor
  "David Anderson <dave@natulte.net>" --maintainer "David Anderson <dave@natulte.net>"
  --description "All-in-one PXE booting" --url "https://github.com/google/netboot"
  ./pixiecore=/usr/bin/pixiecore
env:
- secure: SRcNwt+45QyPS1w9aGxMg9905Y6d9w4mBM29G6iTTnUB5nD7cAk4m+tf834knGSobVXlWcRnTDW8zrHdQ9yX22dPqCpH5qE+qzTmIvxRHrVJRMmPeYvligJ/9jYfHgQbvuRT8cUpIcpCQAla6rw8nXfKTOE3h8XqMP2hdc3DTVOu2HCfKCNco1tJ7is+AIAnFV2Wpsbb3ZsdKFvHvi2RKUfFaX61J1GNt2/XJIlZs8jC6Y1IAC+ftjql9UsAE/WjZ9fL0Ww1b9/LBIIGHXWI3HpVv9WvlhhIxIlJgOVjmU2lbSuj2w/EBDJ9cd1Qe+wJkT3yKzE1NRsNScVjGg+Ku5igJu/XXuaHkIX01+15BqgPduBYRL0atiNQDhqgBiSyVhXZBX9vsgsp0bgpKaBSF++CV18Q9dara8aljqqS33M3imO3I8JmXU10944QA9Wvu7pCYuIzXxhINcDXRvqxBqz5LnFJGwnGqngTrOCSVS2xn7Y+sjmhe1n5cPCEISlozfa9mPYPvMPp8zg3TbATOOM8CVfcpaNscLqa/+SExN3zMwSanjNKrBgoaQcBzGW5mIgSPxhXkWikBgapiEN7+2Y032Lhqdb9dYjH+EuwcnofspDjjMabWxnuJaln+E3/9vZi2ooQrBEtvymUTy4VMSnqwIX5bU7nPdIuQycdWhk=
deploy:
- provider: packagecloud
  repository: pixiecore
  username: danderson
  dist: debian/stretch
  skip_cleanup: true
  package_glob: "*"
  token:
    secure: bKYiaKJgHWEubQOv3Z+xb0CVrxNnIWhf11IsDVPYmypTjqZ1RzqkyPo3VVksRi4IC+fndywXjImT0uYDlwLR26zatIGbSxrNPaawKZYmTR/Xm6/gF5AJlteLWUVZAD5O/Nq5rPxQUy5GGxYiDCmG2EB4Y4EYkjxLTwUyC2pqMKhX6vcR+b967cBrffm+AVz0nOEA684jhDq2+igVo4oG7F7U0745YRbhNZHJhftFmxMT7hvMhi/J7ogq2krPyItIrmnkfW/tlV4PJhiIk1p0VDIXLAGQ98VlG0HjUPdIsMla0d+JkswoGG9JPipb91j5i9XSvKhgHry/xaC1NnyraoHbzmrV7MamwDtK8Y3Rghomu+s3bknYz5B0Ft5ifWz6nTUqs7T/AHlnpK3y/zrK9YuQoZ5zQvMnx4xt97AK/2Au87dCP5ProxKIMiPyrc4rNSPzRe0wJu9opizV0EKS34hTOXsw40/bSuqBtBAenBz2qesWay4IT2gQ8BvhkclHnCEczh/+N/8cEAhXKiptRMm0MkbNVvBvLZOQS+S0npXLq1aTb2ROZ3LA9yEsB5LWUV5lLDoPDmFjGHZ6dHjg7l/ZDc5N0LYAiLv6imaScl5e1np85RStji1M5d4Enx7LD3cqXU5WtGHrz/RoH30in10N9g9dpzf7Glqt6hyeSG4=
  on:
    branch: master
    go: '1.7'
- provider: script
  script: go run scripts/prune_old_versions.go -user=danderson -repo=pixiecore -distro=debian -version=stretch -package=tlsrouter -arch=amd64 -limit=2
  on:
    branch: master
    go: '1.7'
