language: go
go_import_path: go.universe.tf/netboot
go:
  - 1.5
  - 1.6
  - 1.7
  - tip
os:
  - linux
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y atftp
install:
  - go get github.com/Masterminds/glide
  - go get github.com/golang/lint/golint
before_script:
script:
  - glide install
  - GO15VENDOREXPERIMENT=1 go build $(glide novendor)
  - GO15VENDOREXPERIMENT=1 go test $(glide novendor)
  - go vet $(glide novendor)
  - glide novendor | xargs -n1 golint
