[[constraint]]
    name = "github.com/spf13/cobra"
    branch = "master"

[[constraint]]
    name = "github.com/spf13/viper"
    branch = "master"

[[constraint]]
    name = "golang.org/x/crypto"

[[constraint]]
    name = "golang.org/x/net"

[[constraint]]
    name = "github.com/google/go-cmp"
    version = "^0.1.0"
